name: flutter_micro_app
description: A package to speed up the creation of micro apps structure in Flutter applications
version: 0.15.0
homepage: https://github.com/emanuel-braz/flutter_micro_app

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  dart_log: ^1.2.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  
