name: fma_devtools_extension
description: "A extension for Flutter DevTools to support Flutter Micro Apps."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  devtools_extensions: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
