name: fma_devtools_extension
description: "A extension for Flutter DevTools to support Flutter Micro Apps."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.5.1 <4.0.0"
  flutter: '>=3.17.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_micro_app: '>=1.1.0 <2.0.0'

  devtools_extensions: ^0.2.2
  devtools_app_shared: ^0.2.2
  dtd: ^2.2.0
  
  cupertino_icons: ^1.0.2
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
