name: Flutter Analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop, master, release/* ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
#       Issue opened in flutter repo, not fixed yet https://github.com/flutter/flutter/issues/7274#issuecomment-934241151
#     - name: Run Flutter analyze
#       run: flutter analyze lib
    - name: Run Flutter tests
      run: flutter test
