on:
  pull_request:
    branches:
    - "release/*"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: auto-pr-release-develop
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ github.head_ref }}
        destination_branch: "develop"
        pr_title: ":robot: ${{github.event.pull_request.title}}"
        pr_body: "${{github.event.pull_request.body}}"
        pr_template: ""
        pr_reviewer: ""
        pr_assignee: ""
        pr_label: "auto-pr"
        pr_milestone: ""
        pr_draft: true
        pr_allow_empty: true
        github_token: ${{ secrets.GITHUB_TOKEN }}